blog/urls.py
from django.conf.urls import url

from . import views, feeds

urlpatterns = [
    url(r'^(?:page/(?P<page>[0-9]+)/)?$', views.IndexView.as_view(),
        name='index'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<slug>[a-z0-9_-]+)/$',
        views.ArticleView.as_view(), name='article'),
    url(r'^tag/(?P<slug>[a-z0-9_-]+)/(?:page/(?P<page>[0-9]+)/)?$',
        views.TagView.as_view(), name='tag'),
    url(r'^contributor/(?P<slug>[a-z0-9_-]+)/(?:page/(?P<page>[0-9]+)/)?$',
        views.ContributorView.as_view(), name='contributor'),
    url(r'^feed/$', feeds.LatestArticlesFeed(), name='rssfeed'),
    url(r'^(?P<slug>[a-z0-9_-]+)/(?:page/(?P<page>[0-9]+)/)?$',
        views.CategoryView.as_view(), name='category'),
    # url(r'^podcast/feed/$', feeds.PodcastFeed(),
    url(r'^(?P<slug>[a-z0-9_-]+)/feed/$', feeds.CategoryFeed(),
        name='categoryfeed'),
]

inspirationforge/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

admin.site.site_header = "Inspiration Forge Administration"

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^about/',
        TemplateView.as_view(template_name='about.html'),
        name='about'),
    url(r'^', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/_blogroll.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Recommended Reading</h3>
  </div>
  <ul class="list-group">
    <li class="list-group-item">
      <a href="http://www.gnomestew.com/" target="_blank">Gnome Stew</a>
    </li>
    <li class="list-group-item">
      <a href="https://rpgcharacters.wordpress.com/" target="_blank">
        Dyson's Dodecahedron
      </a>
    </li>
    <li class="list-group-item">
      <a href="http://roll1d12.blogspot.com/" target="_blank">
        The Dungeon Dozen
      </a>
    </li>
    <li class="list-group-item">
      <a href="http://www.squidi.net/three/" target="_blank">
        Three Hundred Mechanics
      </a>
    </li>
    <li class="list-group-item">
      <a href="http://www.farmcodegary.com/" target="_blank">
        Farm, Code, Gary (my other blog)
      </a>
    </li>
  </ul>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Recommended Listening</h3>
  </div>
  <ul class="list-group">
    <li class="list-group-item">
      <a href="https://npccast.wordpress.com/" target="_blank">NPC Cast</a>
    </li>
    <li class="list-group-item">
      <a href="http://www.kenandrobintalkaboutstuff.com/" target="_blank">
        Ken and Robin Talk About Stuff
      </a>
    </li>
    <li class="list-group-item">
      <a href="http://www.crucibleofrealms.com/" target="_blank">
        Crucible of Realms
      </a>
    </li>
  </ul>
</div>

templates/snippets/_social_links.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Social</h3>
  </div>
  <ul class="list-group">
    <li class="list-group-item">
      <a href="{% url 'blog:categoryfeed' 'blog' %}" target="_blank">Blog RSS Feed</a>
    </li>
    <li class="list-group-item">
      
      <a href="http://feeds.feedburner.com/inspirationforgepodcast" target="_blank">Pocast RSS Feed</a>
    </li>
    <li class="list-group-item">
      <a href="https://plus.google.com/+GarrisonBenson" target="_blank">
        Google+
      </a>
    </li>
    <li class="list-group-item">
      <a href="https://twitter.com/FarmCodeGary" target="_blank">Twitter</a>
    </li>
    <li class="list-group-item">
      <a href="mailto:benson.garrsion@gmail.com" target="_blank">E-mail</a>
    </li>
  </ul>
</div>