blog/urls.py
from django.conf.urls import url

from . import views, feeds

urlpatterns = [
    url(r'^(?:page/(?P<page>[0-9]+)/)?$', views.IndexView.as_view(),
        name='index'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<slug>[a-z0-9_-]+)/$',
        views.ArticleView.as_view(), name='article'),
    url(r'^tag/(?P<slug>[a-z0-9_-]+)/(?:page/(?P<page>[0-9]+)/)?$',
        views.TagView.as_view(), name='tag'),
    url(r'^contributor/(?P<slug>[a-z0-9_-]+)/(?:page/(?P<page>[0-9]+)/)?$',
        views.ContributorView.as_view(), name='contributor'),
    url(r'^feed/$', feeds.LatestArticlesFeed(), name='rssfeed'),
    url(r'^(?P<slug>[a-z0-9_-]+)/(?:page/(?P<page>[0-9]+)/)?$',
        views.CategoryView.as_view(), name='category'),
    # url(r'^podcast/feed/$', feeds.PodcastFeed(),
    url(r'^(?P<slug>[a-z0-9_-]+)/feed/$', feeds.CategoryFeed(),
        name='categoryfeed'),
]

inspirationforge/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

admin.site.site_header = "Inspiration Forge Administration"

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^about/',
        TemplateView.as_view(template_name='about.html'),
        name='about'),
    url(r'^', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends "base.html" %}

{% block title %}About | {{ block.super }}{% endblock title %}

{% block content %}
  <div class="blog-heading">
    <h2 class="article-title">About</h2>
  </div>
  <img src="http://media.inspirationforge.com/2015/12/inspiration-forge-logo-256px.png" class="img-responsive img-rounded" alt="Inspiration Forge Logo">
  <div class="blog-content">
    <p>
      Welcome to <strong>Inspiration Forge</strong>! This blog is designed to
      provide creative inspiration for nerds (e.g. game masters), and
      maybe the occasional muggle. Our podcast is just launching, and we hope to 
      eventually host some random generators for creative inspiration.
    </p>
    <p>
      Inspiration Forge is an open-source project
      (with
      <a href="https://github.com/FarmCodeGary/InspirationForge" target="_blank">
        source hosted on GitHub</a>)
      created by <a href="https://github.com/FarmCodeGary" target="_blank">Garrison Benson</a>
      and powered by
      <a href="https://www.python.org/" target="_blank">Python 3</a>,
      <a href="https://www.djangoproject.com/" target="_blank">Django</a>,
      <a href="http://www.postgresql.org/" target="_blank">Postgres</a>,
      <a href="http://getbootstrap.com/" target="_blank">Bootstrap 3</a>,
      <a href="http://www.heroku.com/" target="_blank">Heroku</a>,
      <a href="http://gunicorn.org/" target="_blank">Gunicorn</a>,
      and <a href="http://aws.amazon.com/" target="_blank">Amazon AWS</a>.
    </p>
  </div>
{% endblock content %}

templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Inspiration Forge{% endblock title %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    
    <link href="{% static 'css/inspiration-forge.css' %}" rel="stylesheet">
    
    <link rel="icon" type="image/png" href="{% static 'images/inspiration-forge-icon-64px.png' %}" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'blog:index' %}">
            Inspiration Forge
          </a>
          <p class="navbar-text">(Ideas for Nerds!)</p>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'blog:category' 'blog' %}">Blog</a></li>
            <li><a href="{% url 'blog:category' 'podcast' %}">Podcast</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>
      
      <div class="col-sm-8">
        {% block content %}{% endblock content %}
      </div>
      
      <div class="col-sm-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Recent Posts</h3>
          </div>
          <ul class="list-group">
            {% for article in latest_articles %}
              <li class="list-group-item">
                <a href="{{ article.get_absolute_url }}">
                  {{ article.title }}
                </a>
              </li>
            {% endfor %}
          </ul>
        </div>
        
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Recent Comments</h3>
          </div>
          <ul class="list-group">
            {% for comment in latest_comments %}
              <li class="list-group-item">
                {{ comment.name }} on 
                <a href="{{ comment.get_absolute_url }}">
                  {{ comment.article.title }}
                </a>
              </li>
            {% endfor %}
          </ul>
        </div>
        
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Contributors</h3>
          </div>
          <div class="panel-body">
            <p>
              {% for contributor in contributors %}
                <a href="{{ contributor.get_absolute_url }}">
                {{ contributor.display_name }}</a>
                ({{ contributor.num_articles }}){% if not forloop.last %}, {% endif%}
              {% endfor %}
            </p>
          </div>
        </div>
        
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Tags</h3>
          </div>
          <div class="panel-body">
            <p>
              {% for tag in tags %}
                <a href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
                ({{ tag.num_articles }}){% if not forloop.last %}, {% endif%}
              {% endfor %}
            </p>
          </div>
        </div>
        
        {% include "snippets/_social_links.html" %}
        {% include "snippets/_blogroll.html" %}
        
      </div>
    </div>

<footer id="site-footer">
  <div class="container">
    <div class="col-sm-12">
      <div class="well well-sm">
        <p>
          Inspiration Forge &copy; {% now "Y" %} Garrison Benson.
          Powered by
          <a href="https://www.djangoproject.com/" target="_blank">Django</a>
          and
          <a href="http://www.getbootstrap.com" target="_blank">Bootstrap</a>.
        </p>
      </div>
    </div>
  </div>
</footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>